### PR TITLE
Bump up armeria version

### PR DESCRIPTION
**Pull request by amwkr**
- armeria : 1.26.0 -> 1.28.4
 - grpcVersion : 1.58.0 -> 1.63.0
 - grpcKotlinVersion : 1.2.1 -> 1.4.1
 - grpcmock-junit5 : 0.9.4 -> 0.13.0
 - protobuf : 3.20.1 -> 3.25.3
 - add grpc-inprocess

### CODE REVIEW

**Review by taeyeon-Kim — COMMENTED** [review]
@amwkr If you bump up Ameria, could you also check the compatible versions at the link below? 
- https://github.com/line/armeria/blob/armeria-1.28.4/dependencies.toml

**Comment by sohyun-ku** [comment]
@amwkr 
https://github.com/line/armeria/blob/da7f76a7eebf9b03a51ff68a9245269eee4a5a6d/dependencies.toml#L115
We recommend that you also upload the protobuf version and make sure that the scavenger-model module works well.

**Comment by amwkr** [comment]
## Convert to draft
- check protobuf backward compatibility.
- how to test automation old and new version agent <-> collector
- how to test scavenger-agent-python
- PR base change `feature/bump-up-spring-boot-3` to `develop`

#### Bump up spring boot and armeria
- Spring Boot
  - Spring : 5.3.25 -> 6.1.5
  - Spring-Boot : 2.5.12 -> 2.7.8 -> 3.2.4
  - io.spring.dependency-management : 1.0.11.RELEASE -> 1.1.4
  - springDataJdbcPlusVersion : 2.2.3 -> 3.2.4
  - mysql-connector-java:8.0.28 -> com.mysql:mysql-connector-j:8.3.0
    - version not explicit
- Test
  - restAssuredVersion : 4.3.3 -> 5.4.0
  - org.mockito:mockito-inline : 4.3.1
- Armeria
  - armeria : 1.22.1 -> 1.28.4
  - grpcVersion : 1.46.0 -> 1.63.0
    - add grpc-inprocess
  - grpcKotlinVersion : 1.2.1 -> 1.4.1
  - grpcmock-junit5 : 0.9.4 -> 0.13.0
  - protobuf : 3.21.7 -> 3.25.1
  - armeria-spring-boot2-starter -> armeria-spring-boot3-starter
  - armeria-tomcat9 -> armeria-tomcat10

#### Remove unused gradle properties variable
- remove `coroutinesVersion`.
  - found history. This was removed after the test was upgraded.
  - armeria dependency Kotlin Coroutine : 1.6.4 -> 1.7.1

#### Self test use `scavenger-demo`
- scavenger-java-agent:1.1.3-SNAPSHOT -> scavenger-collector:1.1.2
  - local to infra
- scavenger-java-agent:1.1.2 -> scavenger-collector:1.1.3-SANPSHOT
  - local to local

#### not tested yet
- scavenger-old-agent-java
- scavenger-agent-python

**Comment by sohyun-ku** [comment]
@amwkr 

> check protobuf backward compatibility.

Protobuf seems to guarantee backward compatibility in the same language.
plz refer to belows.

refer : https://protobuf.dev/support/cross-version-runtime-guarantee/

**Comment by amwkr** [comment]
### Convert to PR
- PR base change rollback. `develop` to `feature/bump-up-spring-boot-3`

This PR supports the Bump Up "armeria" version.
Bump up "springboot" and "armeria" versions will be handled by @soyun-ku

**Review by sohyun-ku — APPROVED** [review]
LGTM

**Review by taeyeon-Kim — APPROVED** [review]
👍

**Pull request merged**
